# Generated by Django 4.1.6 on 2023-02-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripify", "0003_countries_cities"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tip_prevoza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Tip_sobe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("broj_ljudi", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tipovi_smestaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
    ]
