# Generated by Django 4.1.6 on 2023-02-09 17:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tripify", "0006_tipovi_prevoza"),
    ]

    operations = [
        migrations.CreateModel(
            name="Smestaj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "kategorija",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("internet", models.BooleanField()),
                ("tv", models.BooleanField()),
                ("klima", models.BooleanField()),
                ("sobni_frizider", models.BooleanField()),
                (
                    "cena_prevoza",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(3000),
                            django.core.validators.MinValueValidator(100),
                        ]
                    ),
                ),
                (
                    "grad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripify.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Smestaj_slika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="tripify/static")),
                (
                    "smestaj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tripify.smestaj",
                    ),
                ),
            ],
        ),
    ]
