# Generated by Django 4.1.6 on 2023-02-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tripify", "0007_smestaj_smestaj_slika"),
    ]

    operations = [
        migrations.AddField(
            model_name="smestaj",
            name="tip_smestaja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tripify.tipovi_smestaja",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="smestaj",
            name="tip_sobe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tripify.tip_sobe",
            ),
            preserve_default=False,
        ),
    ]
